### ISSUE TITLE
Running a backup in tar mode causes warnings to be logged.

### ISSUE THREAD

**Issue by gustav-olsen-groupone** [wp-media/backwpup#141]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Running a backup using tar mode generates warnings to the logs. As far as I can tell the warnings do not make the backup invalid.

```
[INFO] BackWPup 4.1.4; A project of WP Media
[INFO] WordPress 6.6.2 on https://example.com/
[INFO] Log Level: Normal
[INFO] BackWPup job: Default Settings (tar)
[INFO] Logfile is: backwpup_log_674b6f_2024-09-27_12-57-10.html
[INFO] Backup file is: 2024-09-27_12-57-10_ND75IAOK02_VT75IAPH02.tar
[27-Sep-2024 12:57:10] 1. Try to backup database …
[27-Sep-2024 12:57:10] Connected to database exampe.com on example.com.mysql
[27-Sep-2024 12:57:10] Added database dump "exampel.com.sql" with 1.02 MB to backup file list
[27-Sep-2024 12:57:10] Database backup done!
[27-Sep-2024 12:57:10] 1. Trying to make a list of folders to back up …
[27-Sep-2024 12:57:13] Added "wp-config.php" to backup file list
[27-Sep-2024 12:57:13] 525 folders to backup.
[27-Sep-2024 12:57:13] 1. Trying to generate a file with installed plugin names …
[27-Sep-2024 12:57:13] Added plugin list file "example.pluginlist.2024-09-27.txt" with 917.00 B to backup file list.
[27-Sep-2024 12:57:13] 1. Trying to generate a manifest file …
[27-Sep-2024 12:57:13] Added manifest.json file with 2.09 KB to backup file list.
[27-Sep-2024 12:57:13] 1. Trying to create backup archive …
[27-Sep-2024 12:57:13] Compressing files as Tar. Please be patient, this may take a moment.
[27-Sep-2024 12:57:13] WARNING: Trying to access array offset on value of type bool
[27-Sep-2024 12:57:13] WARNING: Trying to access array offset on value of type bool
[27-Sep-2024 12:57:13] WARNING: Trying to access array offset on value of type bool
[27-Sep-2024 12:57:13] WARNING: Trying to access array offset on value of type bool
[...]
[27-Sep-2024 12:59:15] WARNING: Trying to access array offset on value of type bool
[27-Sep-2024 12:59:15] WARNING: Trying to access array offset on value of type bool
[27-Sep-2024 12:59:15] WARNING: Trying to access array offset on value of type bool
[27-Sep-2024 12:59:15] Backup archive created.
[27-Sep-2024 12:59:15] Archive size is 5.06 GB.
[27-Sep-2024 12:59:15] 39552 Files with 5.03 GB in Archive.
[27-Sep-2024 12:59:15] WARNING: Job finished with warnings in 125 seconds. Please resolve them for correct execution
```

I tihnk it might be an error per file added to the backup.

**To Reproduce**

1. Create a backup using .tar archiving.
2. Run a backup job
3. Look at the UI, or in the logs.

**Expected behavior**
A backup is generated without warnings.

**Screenshots**
![image](https://github.com/user-attachments/assets/27dd29fd-3c04-45ed-a156-846c01b6353c)

**Comment by Honemo** [comment]
Would it be possible to know the backup configuration (a screenshot of each configuration tab would be perfect) and to find out if there are any other plugins installed? Because I currently can't reproduce this bug.

**Comment by gustav-olsen-groupone** [comment]
![image](https://github.com/user-attachments/assets/62be28d9-3be4-4f3b-b2b0-2db11a3df451)

Here is debug info from the plugin:

```
									WordPress version: 6.6.2
BackWPup version: 4.1.4
PHP version: 8.2.24  (64bit)
MySQL version: 10.6.19-MariaDB-ubu2204
cURL version: 7.81.0
cURL SSL version: OpenSSL/3.0.2
WP-Cron url: https://allans-abuse-site.1prod.one/wp-cron.php
Server self connect: Response Test O.K.
Document root: /customers/4/3/d/allans-abuse-site.1prod.one/httpd.www
Temp folder: /customers/4/3/d/allans-abuse-site.1prod.one/httpd.www/wp-content/uploads/backwpup/ffd401/temp/
Log folder: /customers/4/3/d/allans-abuse-site.1prod.one/httpd.www/wp-content/uploads/backwpup/ffd401/logs/
Server: Apache
Operating System: Linux
PHP SAPI: cgi-fcgi
Current PHP user: allans-abuse-site.1prod.one
Maximum execution time: 300 seconds
BackWPup maximum script execution time: 30 seconds
Alternative WP Cron: Off
Disabled WP Cron: Off
CHMOD Dir: 0755
Server Time: 13:30
Blog Time: 13:30
Blog Timezone: 
Blog Time offset: 0 hours
Blog language: en-US
MySQL Client encoding: utf8
PHP Memory limit: 4294967296
WP memory limit: 40M
WP maximum memory limit: 4294967296
Memory in use: 6.00 MB
Disabled PHP Functions:: disk_total_space,  diskfreespace,  exec,  system,  popen,  proc_open,  proc_nice,  shell_exec,  passthru,  dl
Loaded PHP Extensions:: Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dba, dom, exif, fileinfo, filter, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, random, readline, session, soap, sodium, sqlite3, standard, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib
							
```

**Comment by gustav-olsen-groupone** [comment]
All non first page options are the same.

We also have installed updraft, but other than that no plugins.

My guess is that it will be the PHP version.

**Comment by Honemo** [comment]
I can't reproduce it i'm sorry.
So can you enable the the logs debug level (cf screenshot)

And then provide me the logs provided by a new backup generation please?

![image](https://github.com/user-attachments/assets/5f230607-2c2c-4f93-840e-834ea65e4937)

**Comment by gustav-olsen-groupone** [comment]
[backwpup_log_174244_2024-10-04_11-48-22.log](https://github.com/user-attachments/files/17257790/backwpup_log_174244_2024-10-04_11-48-22.log)

As far as I can see, it doesn't show more details than the excerpt in the original post unfortunately.  I copied the raw text out as I was not allowed to upload a .html file.

**Comment by gustav-olsen-groupone** [comment]
This code is likely written for PHP 7. In PHP 8 - which is used in this case, you have to be more careful with types. That seems like the most obvious explanation here.

Looking at the `class-create-archive.php`-file there is not many places where we index into strings - and even less places which are relevant to tar files. This is one of the few remaining places:

https://github.com/wp-media/backwpup/blob/2d10991a1a58d9dbaffec9f5f997eb55041f587d/inc/class-create-archive.php#L903-L908

The [php.net manual entry for posix_getpwuid](https://www.php.net/manual/en/function.posix-getpwuid.php) says that:
> The function returns false on failure.

A user not existing would be such a case.

It can be reproduced by enabling reporting of errors and trying to run a derived snippet on both version 7 and 8 of PHP.

![Image](https://github.com/user-attachments/assets/66a5703f-4ce2-48ab-b05b-b3f88ba74c2d)

(Source: [onlinephp.io](https://onlinephp.io/?s=LcvLCsIwEIXhfSDvMAshEUSo7rwgLtwVfACRUOzYDthkmKRW3942dXu-_xxO3LJWWqFIECfIQRL5xl7cuSyXe63Ik4uYrKkp8qv6ulxGs4JiYq0W5J8BjsAh0sc1mHjoqbbFZjv7uxJX9x3bHP4_YfAo4ylvN-OrDs09Ez7aAOY6-Q4MrGFuR_sB&v=8.2.20%2C7.0.31))

If you want to reproduce locally, you should make sure that:

1. You have configured PHP to report warnings.
5. You are using a build of PHP 8.
